name: nafta
description: "Mobile wallet for Fuel blockchain and realted ecosystem dApps"

publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.0-282.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.2.1
  mdi: ^5.0.0-nullsafety.0
  simple_icons: ^7.10.0
  dots_indicator: ^2.1.0
  shared_preferences: ^2.0.15
  flutter_tags: ^1.0.0-nullsafety.1
  vibration: ^1.7.4-nullsafety.0
  crypto: ^3.0.2
  bip32: ^2.0.0
  bip39: ^1.0.6
  ed25519_edwards: ^0.3.1
  hex: ^0.2.0
  local_auth: ^2.1.2
  json_rpc_2: ^3.0.1
  json_annotation: ^4.7.0
  equatable: ^2.0.3
  decimal: ^2.0.0
  webview_flutter: ^3.0.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  test: ^1.20.1
  # flutter_test:
  #   sdk: flutter
  # flutter_launcher_name: ^0.0.1
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.4.0
  json_serializable: ^6.1.3
  hive_generator: ^2.0.0
  change_app_package_name: ^1.1.0
  dependency_validator: ^3.0.0
  analyzer: ^5.10.0

flutter_launcher_name:
  name: 'Nafta Wallet'

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/app_logo.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/terms.md
    - assets/images/
    - assets/icons/
    - assets/web_icon/
    - assets/svg_image/
    - assets/lottie_files/
    - assets/contracts/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-LightItalic.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
        - asset: assets/fonts/OpenSans-MediumItalic.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf

flutter_intl:
  enabled: true
